baseURL = "https://kubernetes.io"
title = "Kubernetes"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

disableKinds = ["taxonomy", "taxonomyTerm", "sitemap", "robotsTXT"]

ignoreFiles = [ "^OWNERS$", "README.md", "^node_modules$" ]

contentDir = "content/en"

# TODO(bep)
logo = "/images/favicon.png"

timeout = 500

# Highlighting config.
pygmentsCodeFences = true
pygmentsUseClasses = false
# See https://help.farbox.com/pygments.html
pygmentsStyle = "emacs"

[blackfriday]
hrefTargetBlank = true
fractions = false


# TODO(bep)
[social]
twitter = "kubernetesio"

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[permalinks]
  blog = "/:section/:year/:month/:day/:slug/"


# Be explicit about the output formats. We only want an RSS feed for the sections.
[outputs]
home = [ "HTML"]
page = [ "HTML"]
section = [ "HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
baseName = "feed"	

[params]

time_format_blog = "Monday, January 02, 2006"
description = "Production-Grade Container Orchestration"
showedit = true

fullversion = "v1.10.0"
version = "v1.10"
githubbranch = "master"
docsbranch = "master"
deprecated = false
currentUrl = "https://kubernetes.io/docs/home/"
nextUrl = "http://kubernetes-io-vnext-staging.netlify.com/"

[[params.versions]]
fullversion = "v1.10.0"
version = "v1.10"
githubbranch = "v1.10.0"
docsbranch = "release-1.10"
url = "https://kubernetes.io"

[[params.versions]]
fullversion = "v1.9.0"
version = "v1.9"
githubbranch = "v1.9.0"
docsbranch = "release-1.9"
url = "https://v1-9.docs.kubernetes.io"

[[params.versions]]
fullversion = "v1.8.4"
version = "v1.8"
githubbranch = "v1.8.4"
docsbranch = "release-1.8"
url = "https://v1-8.docs.kubernetes.io"

[[params.versions]]
fullversion = "v1.7.6"
version = "v1.7"
githubbranch = "v1.7.6"
docsbranch = "release-1.7"
url = "https://v1-7.docs.kubernetes.io"

[[params.versions]]
fullversion = "v1.6.8"
version = "v1.6"
githubbranch = "v1.6.8"
docsbranch = "release-1.6"
url = "https://v1-6.docs.kubernetes.io"


[languages]
[languages.en]
title = "Kubernetes"
description = "Production-Grade Container Orchestration"
languageName ="English"
# Weight used for sorting.
weight = 1
[languages.cn]
title = "Kubernetes"
# TODO(bep)
description = "Production-Grade Container Orchestration"
# TODO(bep) this should probably be the name in Chinese
languageName ="Chinese"
weight = 2
contentDir = "content/cn"


